### ISSUE TITLE
build issues with VS2010

### ISSUE THREAD

**Issue by kachanovskiy** [troian/josepp#10]
Hi,

out of the box, josepp does not build with VS2010 due to being written in proper C++11 :), which is a problem for VS2010 as it does not fully implement it.

I have finally managed to compile it with VS2010, so I can provide you a PR to fix this, if the following fixes look ok to you - I had to:
1) remove "final" from class definitions
2) remove type aliases (and replace them with typedefs)
3) remove delegating constructors (copying initialization list from non-default constructor)
4) remove variadic template use in make_shared methods in claims (seems ok, as these methods are never used)
5) change enum classes to plain enums (shouldn't change semantics since enum classes do not contain methods)
6) remove std::bind from lambda use in tests (looks ok as lambda's capture list is empty) - can also be done by replacing lambda with a normal function returning bool

I have also made some minor changes to CMake files:
1) changed explicit use of pkg-config (not supported on Windows) to Unix-only
2) compiler flags also made platform-specific
3) for some reason, jwtpp-test is added as test instead of above configured josepp-test

Let me know if you need this.

Thanks.
Sergey.

**Comment by kachanovskiy** [comment]
this, of course, can be also done by wrapping changed pieces into ifdef's...

**Comment by troian** [comment]
Seems to be reasonable. though VS2010 is quite old.
Lets split it into 2 parts. Firstly push your changes to CMake and then we think about code

**Comment by kachanovskiy** [comment]
I'll put together PRs today.

VS2010 is quite old, yet it is widely adopted in, for example, automotive industry (where I work :)) due to several major libraries/frameworks being built with and supported only when used with VS2010.

**Comment by troian** [comment]
Merged
