### ISSUE TITLE
Use RVO when possible

### ISSUE THREAD

**Issue by not-wlan** [troian/josepp#14]
https://github.com/troian/josepp/blob/e4467db29a33eacc6e747494fc0b1ad762752af6/src/b64.cpp#L213

why pass it by reference when you're gonna make a copy anyway?

also stop moving all return values and let your compiler handle rvo please

**Comment by troian** [comment]
Why don’t you make PR then

**Comment by not-wlan** [comment]
Look, i was just looking for a good jwt library and noticed some things and thought i'd let you know.

**Comment by troian** [comment]
Ok, thank you for reporting.
