### ISSUE TITLE
Missing stringstream include

### ISSUE THREAD

**Issue by steve-cox** [troian/josepp#24]
Hi,

I'm finding I'm getting compilation errors in claims.cpp and tools.cpp:

josepp/src/claims.cpp:63:22: error: invalid use of incomplete type ‘std::stringstream’ {aka ‘class std::__cxx11::basic_stringstream<char>’}
josepp/src/tools.cpp: In function ‘Json::Value jose::unmarshal(const string&)’:
/home/steve/development/p4root/im/extlib/josepp/src/tools.cpp:45:22: error: invalid use of incomplete type ‘std::stringstream’ {aka ‘class std::__cxx11::basic_stringstream<char>’}

Not sure why I get these and you don't (possibly unique to my Fedora 29?), but it's easily fixed by adding the <sstream> include in both files.

Adding the include in both files makes for a clean build/install.

Steve.

**Comment by troian** [comment]
Can you make PR please?

**Comment by kakaly** [comment]
Made a PR for this issue https://github.com/troian/josepp/pull/25

**Comment by troian** [comment]
merged
