### ISSUE TITLE
How to decrypt the payload?

### ISSUE THREAD

**Issue by kakaly** [troian/josepp#27]
Hey,

I have a question about decryption. I can see the APIs to encrypt and verify a JWS. But, I am wondering how to get the payload out of the encrypted data. I do see an API called parse() which returns a shared_ptr to the JWS object. But, there seems to be no public API to get the data out of it. Could you please clarify this. If you have any suggestions for decrypting it, that would be great!

Thanks

**Comment by troian** [comment]
@kakaly JWT does not encode actually. It just has signature which can be verified.
`parse()` returns shared_ptr object with claims (payload you need).

```C++
jws = jose::jws::parse("your bearer")
jws->verify(<your pub key>)
jws->claims().get().any(...)
```

**Comment by troian** [comment]
@kakaly solved?

**Comment by kakaly** [comment]
Perfect! Thanks
