### ISSUE TITLE
How to read keys from strings?

### ISSUE THREAD

**Issue by OlafvdSpek** [troian/josepp#9]
How does one read private and public keys from strings / files?
I saw `jose::rsa::gen(1024)` in the tests but couldn't find how to supply my own keys.

**Comment by troian** [comment]
Refer to tests.cpp:247 static sp_rsa_key gen(int size)
You can read your key from file/string using OpenSSL methods and wrap it into sp_rsa_key.

It's actually good point to handle such by josepp. I'll think about

**Comment by troian** [comment]
@OlafvdSpek You can check referenced commit.
